db:
    image: postgres
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_DB=freedomvote
        - POSTGRES_PASSWORD=freedomvote

web:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/usr/src/app
    ports:
        - "8000:8000"
    links:
        - db
